spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    password: 1234
  jpa:
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      hibernate.globally_quoted_identifiers: true
      hibernate.globally_quoted_identifiers_skip_column_definitions: true
      hibernate.default_batch_fetch_size: 1000
      org:
        hibernate:
          envers:
            revision_field_name: revision_id
            revision_type_field_name: revision_type
            audit_table_suffix: _histories
            store_data_at_delete: true
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
